### ISSUE TITLE
Trying to use this with Vue 3 and Vite

### ISSUE THREAD

**Issue by krry** [danielroe/vue-sanity#148]
**📚 What are you trying to do? Please describe.**
I have a Vue 3 web app that builds with Vite and want to draw in data from my Sanity graph. Vite is an ESM-only build system that doesn't know what `require` means, so it blows up when I try to use this lib to spin up the Sanity Client and fire the fetcher.

**🔍 What have you tried?**
I've tried cloning the next branch and changing the requires to imports. I'm not yet able to get it to build locally. It says it's missing `lib/*`. I can offer a more precise account of these attempts if helpful.

I have also tried to find a way to shoehorn Vite into CommonJS compatibility or interpreting requires, but that's a pretty strong nope.

**ℹ️ Additional context**
Sanity is awesome and I really appreciate you offering this library. Would be rad to get it integrated with Vite, cuz that's super fast.

**Comment by danielroe** [comment]
Thanks @krry. Just to update you, we're just waiting on https://github.com/vuejs/vue-next/pull/3070 to be merged for full ssr support. I've released a version with *experimental* Vite/Vue3 support that you can try by installing `vue-sanity@vite` but would value feedback/issues as I expect there will be some!

**Comment by danielroe** [comment]
This should now be fully working in `0.11.0`. Let me know if you have any issues!

**Comment by krry** [comment]
> This should now be fully working in `0.11.0`. Let me know if you have any issues!

Woo! Thanks, will fire it up shortly.
