### ISSUE TITLE
help: Module '"vue-sanity"' has no exported member 'useSanityClient'.

### ISSUE THREAD

**Issue by vphilot** [danielroe/vue-sanity#180]
**📚 What are you trying to do? Please describe.**
When using the vie-sanity client inside a Vite + TS project, `useSanityClient` doesn't seem to be exported from the package. 

```js
import { useSanityClient } from 'vue-sanity'
```

```bash
Module '"vue-sanity"' has no exported member 'useSanityClient'.ts(2305)
```

**🔍 What have you tried?**
N/A

**ℹ️ Additional context**
    "vue": "^3.0.5",
    "vue-sanity": "^0.10.6"

**Comment by danielroe** [comment]
@vphilot Apologies for the long delay. Would you check with `0.11.0`?

**Comment by vphilot** [comment]
@danielroe  works like a charm!! thank you! :)
