### ISSUE TITLE
help:  Disable chaching.

### ISSUE THREAD

**Issue by vin-ni** [danielroe/vue-sanity#199]
**📚 What are you trying to do? Please describe.**
I've come across issues with caching during dev. I feel there is a 45 seconds delay until i get updates from the cms to show up on nuxt. In general caching is perfect, but for quick tryouts i'd need to turn it off. How can I do that?

**🔍 What have you tried?**
In the documentation I only found how to switch where the caching should happen, but not how to turn it off completely.

Thank you!

**Comment by danielroe** [comment]
@vin-ni Sounds like you probably want to turn off `useCdn`, which you can do like so:

```js
import { useSanityClient } from 'vue-sanity'

export default {
  name: 'App',
  setup() {
    useSanityClient({
      projectId: 'myprojectid',
      dataset: 'production',
      useCdn: process.env.NODE_ENV === 'production',
    })
  },
}
```

If that doesn't solve the issue for you, I'd appreciate a reproduction. 🙏

**Comment by vin-ni** [comment]
Works! Thanks a lot!
