### ISSUE TITLE
fix: Can't import named export 'computed' from EcmaScript

### ISSUE THREAD

**Issue by jbrainz** [danielroe/vue-sanity#213]
**🐛 The bug**
Can't import the named export 'computed' from non EcmaScript module (only default export is available)

i  am using vue 3. but when i try to compile my project i get this error.
![image](https://user-images.githubusercontent.com/24702087/154943419-0791f0ac-0145-4513-b6a7-7788ace88202.png)

**Comment by danielroe** [comment]
Are you using Nuxt 3?

**Comment by jbrainz** [comment]
No

**Comment by danielroe** [comment]
This originates from the `vue-demi` import, and should be resolved in your bundler config: see https://github.com/vueuse/vueuse/issues/718#issuecomment-913319680 and https://github.com/vueuse/vue-demi/issues/63.
