### ISSUE TITLE
feat: Vite-SSG support

### ISSUE THREAD

**Issue by jacenre** [danielroe/vue-sanity#221]
**🆒 Your use case**
Correctly prefetching when using vite-ssg. Currently it cannot detect it and will run into errors (`window is not defined`).
A small change could fix it.

**🆕 The solution you'd like**
Very simply check if vite-ssg is currently generating the pages, and if so request it.
PR already exists for that: https://github.com/danielroe/vue-sanity/pull/220

**🔍 Alternatives you've considered**
- Replacing the check for the $isServer variable with `typeof window !== 'undefined'`
- Figuring out how to inject the $isServer variable as the current code looks for that to determine if the call is server side or client side.
This would be impossible without changing the Vite-SSG source code. Just changing a single line here would already solve it.

**Comment by danielroe** [comment]
Resolved in #220 - thanks!
